### ISSUE TITLE
W3C manifest spec throws

### ISSUE THREAD

**Issue by marcoscaceres** [iherman/respec2epub#9] opened 2015-09-10 19:02 UTC
Trying to gen from http://w3c.github.io/manifest/ I get:

```
Epub Generator Exception

Traceback (most recent call last):
  File "/home/ivan/htdocs/cgi-bin/epub-generator.py", line 176, in 
    Generator().process()
  File "/home/ivan/htdocs/cgi-bin/epub-generator.py", line 162, in process
    wrapper = self.generate_ebook()
  File "/home/ivan/htdocs/cgi-bin/epub-generator.py", line 150, in generate_ebook
    logger=logger
  File "/home/ivan/lib/python/rp2epub/doc2epub.py", line 79, in __init__
    session = HttpSession(CONVERTER + url if is_respec else url, raise_exception=True)
  File "/home/ivan/lib/python/rp2epub/utils.py", line 386, in __init__
    handle_exception("%s cannot be reached" % url)
  File "/home/ivan/lib/python/rp2epub/utils.py", line 375, in handle_exception
    raise R2EError(message)
R2EError: https://labs.w3.org/spec-generator/?type=respec&url=http://w3c.github.io/manifest/ cannot be reached
```

**Comment by iherman** [comment] 2015-09-11 04:44
@marcoscaceres:

Yes, I have seen that yesterday, but it seems that the spec generator itself times out! I tested the generator directly... And I do not know what happens there...

**Comment by iherman** [comment] 2015-09-11 13:30
@marcoscaceres : 

I just tried again to run:

https://labs.w3.org/spec-generator/?type=respec&url=http://w3c.github.io/manifest/

and I get a "time out" reply on the screen... to be on the safe side, I tried with another document that I have used for testing, at the URI:

https://labs.w3.org/spec-generator/?type=respec&url=http://w3c.github.io/csvw/syntax/index.html

and it goes wrong again. I am afraid the problem is with the spec-generator. Who can handle that?

/Cc: @darobin

**Comment by darobin** [comment] 2015-09-11 13:48
If the spec-generator is down or misbehaving, I think talking to @dontcallmedom might help.

**Comment by dontcallmedom** [comment] 2015-09-14 11:35
There is a bug in respec when used with phantomjs that is the likely cause of this failure; I have a pending pull request that fixes the bug: https://github.com/w3c/respec/pull/500
Hopefully @marcoscaceres can review/merge it soon.

**Comment by iherman** [comment] 2015-09-14 11:38
Thanks a lot, Dominique!

**Comment by iherman** [comment] 2015-09-15 10:03
@marcoscaceres, the service on spec generator has been restored, and the epub generator works now and generates the epub file for  http://w3c.github.io/manifest/. Closing the issue.

(And thanks to @dontcallmedom, too)

**Closed as completed by iherman** 2015-09-15 10:03 UTC
